kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 0
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
      - name: spark-master
        image: dperdices/spark-master:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
        - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: LoadBalancer
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
  - name: spark
    port: 7077
    targetPort: 7077
  selector:
    component: spark-master